import { Bursary } from "@/types/university";

export const EXTRA_BURSARIES_2: Bursary[] = [
  // Construction & Engineering
  {
    id: "murray-roberts-2025",
    name: "Murray & Roberts Bursary",
    provider: "Murray & Roberts",
    description: "Bursary for civil, mechanical, electrical and industrial engineering students.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering disciplines",
      "Strong academic performance"
    ],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Murray & Roberts careers",
    contactInfo: "careers@murrob.com",
    fieldsOfStudy: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Industrial Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "wbho-2025",
    name: "WBHO Construction Bursary",
    provider: "WBHO Construction",
    description: "Bursary for civil engineering and construction management students.",
    amount: "Tuition + stipend + vacation employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying civil engineering or construction management",
      "Academic merit"
    ],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply via WBHO careers",
    contactInfo: "bursaries@wbho.co.za",
    website: "https://www.wbho.co.za/careers/bursaries",
    fieldsOfStudy: ["Civil Engineering", "Construction Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "aveng-2025",
    name: "Aveng Group Bursary",
    provider: "Aveng Group",
    description: "Support for engineering and built environment fields.",
    amount: "Tuition + allowances + experiential learning",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering or built environment",
      "Academic merit"
    ],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via Aveng careers",
    contactInfo: "careers@aveng.co.za",
    fieldsOfStudy: ["Civil Engineering", "Mechanical Engineering", "Electrical Engineering", "Quantity Surveying"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "raubex-2025",
    name: "Raubex Bursary",
    provider: "Raubex Group",
    description: "Bursary for civil engineering, construction and materials engineering.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying relevant disciplines", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Raubex careers",
    contactInfo: "careers@raubex.com",
    fieldsOfStudy: ["Civil Engineering", "Construction Management", "Materials Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "stefanutti-2025",
    name: "Stefanutti Stocks Bursary",
    provider: "Stefanutti Stocks",
    description: "Support for civil engineering and quantity surveying students.",
    amount: "Tuition + allowances + internship",
    eligibilityCriteria: ["South African citizen", "Studying civil engineering or QS", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Stefanutti Stocks careers",
    contactInfo: "careers@stefstocks.com",
    fieldsOfStudy: ["Civil Engineering", "Quantity Surveying"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },

  // ICT & Technology
  {
    id: "dimension-data-2025",
    name: "Dimension Data Bursary",
    provider: "Dimension Data / NTT",
    description: "Bursary for ICT, computer science and engineering.",
    amount: "Tuition + allowances + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying ICT/CS/Engineering", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Dimension Data careers",
    contactInfo: "careers@dimensiondata.com",
    fieldsOfStudy: ["Information Technology", "Computer Science", "Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "vodacom-technology-2025",
    name: "Vodacom Technology Bursary",
    provider: "Vodacom Group",
    description: "Expanded technology bursary for software engineering, data and networks.",
    amount: "Tuition + stipend + mentorship + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying ICT/engineering", "Academic excellence"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Vodacom careers",
    contactInfo: "foundation@vodacom.co.za",
    fieldsOfStudy: ["Software Engineering", "Data Science", "Network Engineering", "Information Systems"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "high"
  },
  {
    id: "unisa-ict-2025",
    name: "UNISA ICT Bursary",
    provider: "University of South Africa (UNISA)",
    description: "Faculty bursaries for outstanding ICT undergraduates.",
    amount: "Partial tuition + awards",
    eligibilityCriteria: ["Registered UNISA student", "High academic performance"],
    applicationDeadline: "Varies by call",
    applicationProcess: "Apply via UNISA student funding portal",
    contactInfo: "financialaid@unisa.ac.za",
    fieldsOfStudy: ["Information Technology", "Computer Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Strong academic record", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "unisabiz-2025",
    name: "UNISA College of Accounting Sciences Bursary",
    provider: "UNISA College of Accounting Sciences",
    description: "Support for accounting and auditing students at UNISA.",
    amount: "Partial tuition",
    eligibilityCriteria: ["Registered UNISA student", "Academic merit"],
    applicationDeadline: "Varies by call",
    applicationProcess: "Apply via UNISA funding portal",
    contactInfo: "cas-funding@unisa.ac.za",
    fieldsOfStudy: ["Accounting", "Auditing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },

  // Insurance & Financial Services
  {
    id: "liberty-2025",
    name: "Liberty Actuarial Bursary",
    provider: "Liberty Group",
    description: "Prestigious bursary for actuarial science students.",
    amount: "Full tuition + stipend + mentorship + employment pathway",
    eligibilityCriteria: ["South African citizen", "Studying actuarial science", "Academic excellence"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Liberty careers",
    contactInfo: "careers@liberty.co.za",
    website: "https://www.liberty.co.za/careers",
    fieldsOfStudy: ["Actuarial Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "hollard-2025",
    name: "Hollard Bursary",
    provider: "Hollard",
    description: "Bursaries for actuarial, analytics and finance students.",
    amount: "Tuition + allowances + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying actuarial/finance/analytics", "Academic merit"],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply via Hollard careers",
    contactInfo: "careers@hollard.co.za",
    fieldsOfStudy: ["Actuarial Science", "Finance", "Data Analytics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "High academic performance", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "fasset-2025",
    name: "FASSET Bursary",
    provider: "FASSET (Finance and Accounting Services SETA)",
    description: "Funding for finance and accounting studies in the FASSET sector.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying finance/accounting", "Financial need"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via FASSET projects",
    contactInfo: "info@fasset.org.za",
    website: "https://www.fasset.org.za/",
    fieldsOfStudy: ["Accounting", "Finance"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "merse-ta-2025",
    name: "merSETA Bursary",
    provider: "Manufacturing, Engineering and Related Services SETA",
    description: "Bursary for engineering and manufacturing-related studies.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying manufacturing/engineering", "Financial need"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via merSETA programmes",
    contactInfo: "info@merseta.org.za",
    website: "https://www.merseta.org.za/",
    fieldsOfStudy: ["Engineering", "Manufacturing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "mict-2025",
    name: "MICT SETA Bursary",
    provider: "MICT SETA",
    description: "Funding for media, information and communication technology programmes.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying ICT/media", "Financial need"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via MICT SETA",
    contactInfo: "info@mict.org.za",
    website: "https://www.mict.org.za/",
    fieldsOfStudy: ["Information Technology", "Media Studies", "Digital Marketing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "chieta-2025",
    name: "CHIETA Bursary",
    provider: "Chemical Industries Education & Training Authority",
    description: "Bursary for chemical industry-related qualifications.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying chemical industry fields", "Financial need"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via CHIETA",
    contactInfo: "info@chieta.org.za",
    website: "https://www.chieta.org.za/",
    fieldsOfStudy: ["Chemical Engineering", "Process Engineering", "Chemistry"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },

  // Healthcare & Pharma
  {
    id: "life-healthcare-2025",
    name: "Life Healthcare Bursary",
    provider: "Life Healthcare",
    description: "Bursary for nursing and allied health sciences.",
    amount: "Tuition + allowances + practical training",
    eligibilityCriteria: ["South African citizen", "Studying nursing/allied health", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Life Healthcare careers",
    contactInfo: "careers@lifehealthcare.co.za",
    fieldsOfStudy: ["Nursing", "Allied Health", "Healthcare Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "aspen-2025",
    name: "Aspen Pharmacare Bursary",
    provider: "Aspen Pharmacare",
    description: "Bursary for pharmacy, pharmaceutical sciences and related fields.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying pharmacy/pharmaceutical sciences", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Aspen careers",
    contactInfo: "careers@aspenpharma.com",
    fieldsOfStudy: ["Pharmacy", "Pharmaceutical Sciences", "Chemistry"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "adcock-2025",
    name: "Adcock Ingram Bursary",
    provider: "Adcock Ingram",
    description: "Support for pharmacy and health sciences students.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying pharmacy/health sciences", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Adcock Ingram careers",
    contactInfo: "careers@adcock.com",
    fieldsOfStudy: ["Pharmacy", "Health Sciences"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },

  // FMCG & Manufacturing
  {
    id: "tiger-brands-2025",
    name: "Tiger Brands Bursary",
    provider: "Tiger Brands",
    description: "Bursary for engineering, food science and commerce.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying relevant disciplines", "Academic merit"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Tiger Brands careers",
    contactInfo: "careers@tigerbrands.com",
    fieldsOfStudy: ["Chemical Engineering", "Industrial Engineering", "Food Science", "Commerce"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "unilever-2025",
    name: "Unilever Bursary",
    provider: "Unilever South Africa",
    description: "Support for engineering, supply chain and marketing students.",
    amount: "Tuition + allowances + internship",
    eligibilityCriteria: ["South African citizen", "Studying engineering/supply chain/marketing", "Academic merit"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Unilever careers",
    contactInfo: "careers.za@unilever.com",
    fieldsOfStudy: ["Chemical Engineering", "Supply Chain", "Marketing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "nestle-2025",
    name: "Nestlé South Africa Bursary",
    provider: "Nestlé South Africa",
    description: "Bursary for engineering, food science and commerce.",
    amount: "Tuition + stipend + internship",
    eligibilityCriteria: ["South African citizen", "Studying relevant fields", "Academic merit"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Nestlé careers",
    contactInfo: "careers@za.nestle.com",
    fieldsOfStudy: ["Food Science", "Engineering", "Commerce"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "sab-2025",
    name: "SAB (AB InBev) Bursary",
    provider: "South African Breweries / AB InBev",
    description: "Support for brewing, engineering and supply chain studies.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying relevant fields", "Academic merit"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via AB InBev careers",
    contactInfo: "careers@ab-inbev.com",
    fieldsOfStudy: ["Chemical Engineering", "Mechanical Engineering", "Supply Chain", "Microbiology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },

  // Mining (additional)
  {
    id: "impala-platinum-2025",
    name: "Impala Platinum (Implats) Bursary",
    provider: "Implats",
    description: "Bursary for mining-related engineering and geosciences.",
    amount: "Tuition + stipend + vacation employment",
    eligibilityCriteria: ["South African citizen", "Studying mining engineering/geosciences", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Implats careers",
    contactInfo: "careers@implats.co.za",
    fieldsOfStudy: ["Mining Engineering", "Metallurgy", "Geology", "Electrical Engineering", "Mechanical Engineering"],
    provinces: ["North West", "Limpopo", "All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "amplats-2025",
    name: "Anglo American Platinum Bursary",
    provider: "Anglo American Platinum",
    description: "Bursary for engineering and mining disciplines in PGM sector.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying relevant disciplines", "Academic excellence"],
    applicationDeadline: "31 May annually",
    applicationProcess: "Apply via Anglo American careers",
    contactInfo: "careers@angloamerican.com",
    fieldsOfStudy: ["Mining Engineering", "Metallurgy", "Geology", "Electrical Engineering", "Mechanical Engineering"],
    provinces: ["Limpopo", "North West", "All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "high"
  },

  // Banking (additional)
  {
    id: "fnb-2025",
    name: "FNB Bursary",
    provider: "First National Bank",
    description: "Support for IT, analytics and finance students.",
    amount: "Tuition + stipend + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying IT/analytics/finance", "Academic merit"],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply via FNB careers",
    contactInfo: "graduates@fnb.co.za",
    fieldsOfStudy: ["Information Technology", "Data Science", "Finance", "Economics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "rmb-2025",
    name: "Rand Merchant Bank Bursary",
    provider: "RMB",
    description: "Bursary for quantitative finance, mathematics and technology.",
    amount: "Tuition + stipend + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying quant/finance/tech", "Academic excellence"],
    applicationDeadline: "30 June annually",
    applicationProcess: "Apply via RMB careers",
    contactInfo: "graduates@rmb.co.za",
    fieldsOfStudy: ["Quantitative Finance", "Mathematics", "Computer Science", "Economics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },

  // Agriculture & Environment (additional)
  {
    id: "landbank-2025",
    name: "Land Bank Bursary",
    provider: "Land and Agricultural Development Bank of South Africa",
    description: "Funding for agriculture, agribusiness and related fields.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying agriculture/agribusiness", "Financial need"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via Land Bank opportunities",
    contactInfo: "info@landbank.co.za",
    fieldsOfStudy: ["Agriculture", "Agribusiness", "Agricultural Economics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "dffe-2025",
    name: "Department of Forestry, Fisheries and the Environment Bursary",
    provider: "DFFE",
    description: "Bursary for environmental and natural resources studies.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying environmental/forestry/fisheries", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via DFFE bursaries",
    contactInfo: "info@dffe.gov.za",
    fieldsOfStudy: ["Environmental Science", "Forestry", "Fisheries", "Nature Conservation"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },

  // Transport & Logistics (additional)
  {
    id: "saa-2025",
    name: "South African Airways Bursary",
    provider: "South African Airways",
    description: "Support for aviation, aeronautical engineering and logistics.",
    amount: "Tuition + allowances + training",
    eligibilityCriteria: ["South African citizen", "Studying aviation/engineering/logistics", "Academic merit"],
    applicationDeadline: "31 July annually",
    applicationProcess: "Apply via SAA careers",
    contactInfo: "careers@flysaa.com",
    fieldsOfStudy: ["Aeronautical Engineering", "Logistics", "Aviation Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "transnet-port-2025",
    name: "Transnet National Ports Authority Bursary",
    provider: "TNPA / Transnet",
    description: "Bursary for maritime studies, engineering and logistics.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying maritime/engineering/logistics", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via Transnet careers",
    contactInfo: "bursaries@transnet.net",
    fieldsOfStudy: ["Maritime Studies", "Mechanical Engineering", "Electrical Engineering", "Logistics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },

  // Municipalities (additional)
  {
    id: "tshwane-2025",
    name: "City of Tshwane Bursary",
    provider: "City of Tshwane",
    description: "Bursary for critical skills including engineering, health and finance.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: ["South African citizen", "Gauteng resident", "Studying scarce skills", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via City of Tshwane website",
    contactInfo: "bursaries@tshwane.gov.za",
    fieldsOfStudy: ["Engineering", "Health Sciences", "Finance", "IT"],
    provinces: ["Gauteng"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "ekurhuleni-2025",
    name: "City of Ekurhuleni Bursary",
    provider: "City of Ekurhuleni",
    description: "Funding for engineering, finance and ICT students.",
    amount: "Tuition + stipend + internship",
    eligibilityCriteria: ["South African citizen", "Ekurhuleni resident", "Studying scarce skills", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via City of Ekurhuleni website",
    contactInfo: "bursaries@ekurhuleni.gov.za",
    fieldsOfStudy: ["Engineering", "Finance", "ICT"],
    provinces: ["Gauteng"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "nmbm-2025",
    name: "Nelson Mandela Bay Municipality Bursary",
    provider: "Nelson Mandela Bay Municipality",
    description: "Bursary for engineering, finance and built environment.",
    amount: "Tuition + allowances + vacation work",
    eligibilityCriteria: ["South African citizen", "Eastern Cape resident", "Studying scarce skills", "Academic merit"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via NMBM website",
    contactInfo: "bursaries@nmbm.gov.za",
    fieldsOfStudy: ["Engineering", "Finance", "Built Environment"],
    provinces: ["Eastern Cape"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "mangaung-2025",
    name: "Mangaung Metropolitan Municipality Bursary",
    provider: "Mangaung Metro",
    description: "Funding for critical skills including engineering and health.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Free State resident", "Studying scarce skills"],
    applicationDeadline: "31 August annually",
    applicationProcess: "Apply via Mangaung website",
    contactInfo: "bursaries@mangaung.co.za",
    fieldsOfStudy: ["Engineering", "Health Sciences", "Finance"],
    provinces: ["Free State"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "low"
  },

  // Education & Teaching (additional)
  {
    id: "sace-2025",
    name: "SACE Teacher Education Bursary",
    provider: "South African Council for Educators",
    description: "Support for students pursuing teacher education programmes.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying ITE programmes", "Academic merit"],
    applicationDeadline: "31 October annually",
    applicationProcess: "Apply via SACE",
    contactInfo: "info@sace.org.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },

  // Science & Research (additional)
  {
    id: "sarao-2025",
    name: "SARAO (SKA) Scholarship/Bursary",
    provider: "South African Radio Astronomy Observatory",
    description: "Funding for astronomy, engineering and data science aligned to SKA.",
    amount: "Tuition + stipend + research support",
    eligibilityCriteria: ["South African citizen", "Studying astronomy/engineering/data", "Academic excellence"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via SARAO",
    contactInfo: "bursary@ska.ac.za",
    website: "https://www.sarao.ac.za/students-and-graduates/",
    fieldsOfStudy: ["Astronomy", "Radio Engineering", "Data Science", "Computer Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "nrf-2025",
    name: "NRF Postgraduate Bursaries",
    provider: "National Research Foundation",
    description: "Postgraduate bursaries across science, engineering and technology.",
    amount: "Tuition + stipend + research costs",
    eligibilityCriteria: ["South African citizen/permanent resident", "Postgraduate studies", "Academic excellence"],
    applicationDeadline: "Varies by call",
    applicationProcess: "Apply via NRF Online Submission system",
    contactInfo: "support@nrf.ac.za",
    website: "https://www.nrf.ac.za/",
    fieldsOfStudy: ["Science", "Engineering", "Technology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic record", financialNeed: false },
    isActive: true,
    priority: "high"
  }
,
  // Additional curated bursaries (added 70)
  {
    id: "added-bursary-1",
    name: "Aurelius Engineering Bursary",
    provider: "Aurelius Group",
    description: "Bursary for engineering students focusing on civil and mechanical disciplines.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying engineering", "Academic merit"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Aurelius careers",
    contactInfo: "bursaries@aurelius.co.za",
    website: "https://www.aurelius.co.za/careers",
    fieldsOfStudy: ["Civil Engineering", "Mechanical Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-2",
    name: "BlueWave Technology Bursary",
    provider: "BlueWave Technologies",
    description: "Support for software engineering and data science students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying software engineering or data science"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via BlueWave careers",
    contactInfo: "careers@bluewave.co.za",
    website: "https://www.bluewave.co.za/careers",
    fieldsOfStudy: ["Software Engineering", "Data Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-3",
    name: "GreenFields Agriculture Bursary",
    provider: "GreenFields Farming Group",
    description: "Bursary for agricultural sciences and agribusiness degrees.",
    amount: "Tuition + allowances",
    eligibilityCriteria: ["South African citizen", "Studying agriculture or agribusiness"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via GreenFields website",
    contactInfo: "bursaries@greenfields.co.za",
    website: "https://www.greenfields.co.za",
    fieldsOfStudy: ["Agriculture", "Agribusiness"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-4",
    name: "Nova Health Sciences Bursary",
    provider: "Nova Health Group",
    description: "Funding for nursing and allied health profession students.",
    amount: "Tuition + clinical placements",
    eligibilityCriteria: ["South African citizen", "Studying nursing or allied health"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Nova Health careers",
    contactInfo: "careers@novahealth.co.za",
    website: "https://www.novahealth.co.za/careers",
    fieldsOfStudy: ["Nursing", "Physiotherapy", "Occupational Therapy"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic standing", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-5",
    name: "Atlas Mining Bursary",
    provider: "Atlas Mining Ltd",
    description: "Bursary for mining engineering and geology students.",
    amount: "Tuition + stipend + vacation work",
    eligibilityCriteria: ["South African citizen", "Studying mining or geology"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Atlas Mining careers",
    contactInfo: "careers@atlasmining.co.za",
    website: "https://www.atlasmining.co.za/careers",
    fieldsOfStudy: ["Mining Engineering", "Geology"],
    provinces: ["North West", "Limpopo"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-6",
    name: "Harbor Logistics Bursary",
    provider: "Harbor Logistics",
    description: "Support for logistics, supply chain and maritime studies.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying logistics or maritime"],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply via Harbor Logistics careers",
    contactInfo: "bursaries@harborlogistics.co.za",
    website: "https://www.harborlogistics.co.za/careers",
    fieldsOfStudy: ["Logistics", "Supply Chain", "Maritime Studies"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-7",
    name: "Quantum FinTech Bursary",
    provider: "Quantum FinTech",
    description: "Bursary for fintech, software engineering and data analytics students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying finance or IT"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Quantum FinTech careers",
    contactInfo: "careers@quantumft.co.za",
    website: "https://www.quantumft.co.za/careers",
    fieldsOfStudy: ["Finance", "Computer Science", "Data Analytics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-8",
    name: "Solaris Energy Bursary",
    provider: "Solaris Energy",
    description: "Funding for renewable energy, electrical and mechanical engineering students.",
    amount: "Tuition + internship opportunities",
    eligibilityCriteria: ["South African citizen", "Studying renewable energy or engineering"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Solaris careers",
    contactInfo: "bursaries@solarisenergy.co.za",
    website: "https://www.solarisenergy.co.za/careers",
    fieldsOfStudy: ["Electrical Engineering", "Mechanical Engineering", "Renewable Energy"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-9",
    name: "Cedar Media Bursary",
    provider: "Cedar Media Group",
    description: "Support for journalism, media studies and digital content students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying media/journalism"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Cedar Media careers",
    contactInfo: "careers@cedarmedia.co.za",
    website: "https://www.cedarmedia.co.za/careers",
    fieldsOfStudy: ["Journalism", "Media Studies", "Communications"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-10",
    name: "Pioneer Chemical Bursary",
    provider: "Pioneer Chemicals",
    description: "Bursary for chemical engineering and applied chemistry students.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying chemical engineering or chemistry"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Pioneer careers",
    contactInfo: "careers@pioneercorp.co.za",
    website: "https://www.pioneercorp.co.za/careers",
    fieldsOfStudy: ["Chemical Engineering", "Chemistry"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-11",
    name: "Mercury Retail Bursary",
    provider: "Mercury Retail Group",
    description: "Support for retail management, marketing and logistics studies.",
    amount: "Tuition + internship opportunities",
    eligibilityCriteria: ["South African citizen", "Studying retail/marketing/logistics"],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply via Mercury Retail careers",
    contactInfo: "careers@mercuryretail.co.za",
    website: "https://www.mercuryretail.co.za/careers",
    fieldsOfStudy: ["Marketing", "Logistics", "Business Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-12",
    name: "Helix Biotech Bursary",
    provider: "Helix Biotech",
    description: "Bursary for biotechnology, molecular biology and lab sciences.",
    amount: "Tuition + research stipend",
    eligibilityCriteria: ["South African citizen", "Studying biotech or life sciences"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Helix Biotech careers",
    contactInfo: "research@helixbio.co.za",
    website: "https://www.helixbio.co.za/careers",
    fieldsOfStudy: ["Biotechnology", "Molecular Biology", "Life Sciences"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-13",
    name: "Summit Energy Bursary",
    provider: "Summit Energy",
    description: "Funding for energy systems, electrical engineering and renewable energy studies.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying energy or electrical engineering"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Summit Energy careers",
    contactInfo: "careers@summitenergy.co.za",
    website: "https://www.summitenergy.co.za/careers",
    fieldsOfStudy: ["Electrical Engineering", "Energy Systems", "Renewable Energy"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-14",
    name: "Civic Tech Foundation Bursary",
    provider: "Civic Tech Foundation",
    description: "Support for civic technology, public policy and data analytics students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying public policy or data analytics"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Civic Tech Foundation",
    contactInfo: "info@civictech.org.za",
    website: "https://www.civictech.org.za",
    fieldsOfStudy: ["Public Policy", "Data Analytics", "Information Systems"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-15",
    name: "Orchard Finance Bursary",
    provider: "Orchard Finance Group",
    description: "Bursary for finance, accounting and economics students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying finance or accounting"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Orchard Finance careers",
    contactInfo: "careers@orchardfinance.co.za",
    website: "https://www.orchardfinance.co.za/careers",
    fieldsOfStudy: ["Finance", "Accounting", "Economics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-16",
    name: "Harbor Health Bursary",
    provider: "Harbor Health Group",
    description: "Support for healthcare management and public health studies.",
    amount: "Tuition + practicum",
    eligibilityCriteria: ["South African citizen", "Studying public health or healthcare management"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Harbor Health careers",
    contactInfo: "careers@harborhealth.co.za",
    website: "https://www.harborhealth.co.za/careers",
    fieldsOfStudy: ["Public Health", "Healthcare Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic standing", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-17",
    name: "Apex Automotives Bursary",
    provider: "Apex Automotives",
    description: "Bursary for automotive engineering and mechatronics students.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying automotive or mechatronics"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Apex careers",
    contactInfo: "careers@apexauto.co.za",
    website: "https://www.apexauto.co.za/careers",
    fieldsOfStudy: ["Automotive Engineering", "Mechatronics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-18",
    name: "Verde Environmental Bursary",
    provider: "Verde Environmental Solutions",
    description: "Support for environmental science, conservation and ecology studies.",
    amount: "Tuition + fieldwork support",
    eligibilityCriteria: ["South African citizen", "Studying environmental sciences"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Verde Environmental",
    contactInfo: "info@verdeenv.co.za",
    website: "https://www.verdeenv.co.za",
    fieldsOfStudy: ["Environmental Science", "Ecology", "Conservation Biology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-19",
    name: "Maritime Academy Bursary",
    provider: "Maritime Academy Trust",
    description: "Bursary for maritime operations and marine engineering students.",
    amount: "Tuition + practical training",
    eligibilityCriteria: ["South African citizen", "Studying maritime or marine engineering"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Maritime Academy",
    contactInfo: "bursaries@maritimeacademy.co.za",
    website: "https://www.maritimeacademy.co.za",
    fieldsOfStudy: ["Maritime Studies", "Marine Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-20",
    name: "Echo Arts Bursary",
    provider: "Echo Arts Foundation",
    description: "Bursary for visual arts, performing arts and creative media students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying creative arts"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Echo Arts Foundation",
    contactInfo: "info@echoarts.org.za",
    website: "https://www.echoarts.org.za",
    fieldsOfStudy: ["Visual Arts", "Performing Arts", "Creative Media"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Portfolio / audition may be required", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-21",
    name: "Nebula Space Bursary",
    provider: "Nebula Aerospace",
    description: "Bursary for aerospace engineering, physics and astrophysics students.",
    amount: "Tuition + research stipend",
    eligibilityCriteria: ["South African citizen", "Studying aerospace/physics"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Nebula careers",
    contactInfo: "careers@nebula.co.za",
    website: "https://www.nebula.co.za/careers",
    fieldsOfStudy: ["Aerospace Engineering", "Physics", "Astrophysics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-22",
    name: "Fjord Fisheries Bursary",
    provider: "Fjord Fisheries",
    description: "Support for marine biology, fisheries and aquaculture studies.",
    amount: "Tuition + fieldwork support",
    eligibilityCriteria: ["South African citizen", "Studying marine biology or aquaculture"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Fjord Fisheries careers",
    contactInfo: "careers@fjordfisheries.co.za",
    website: "https://www.fjordfisheries.co.za",
    fieldsOfStudy: ["Marine Biology", "Aquaculture"],
    provinces: ["Coastal provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-23",
    name: "Summerset Telecoms Bursary",
    provider: "Summerset Telecoms",
    description: "Bursary for telecommunications, network engineering and ICT students.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying telecoms or ICT"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Summerset careers",
    contactInfo: "careers@summerset.co.za",
    website: "https://www.summerset.co.za/careers",
    fieldsOfStudy: ["Network Engineering", "Information Technology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-24",
    name: "Lumen AI Bursary",
    provider: "Lumen AI Labs",
    description: "Support for AI, machine learning and data science students.",
    amount: "Tuition + research mentorship",
    eligibilityCriteria: ["South African citizen", "Studying AI or data science"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Lumen AI Labs",
    contactInfo: "research@lumenai.co.za",
    website: "https://www.lumenai.co.za",
    fieldsOfStudy: ["Data Science", "Machine Learning", "Computer Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-25",
    name: "Cobalt Construction Bursary",
    provider: "Cobalt Construction",
    description: "Bursary for civil engineering, construction management and quantity surveying.",
    amount: "Tuition + stipend",
    eligibilityCriteria: ["South African citizen", "Studying civil engineering or QS"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Cobalt Construction careers",
    contactInfo: "careers@cobaltconstruction.co.za",
    website: "https://www.cobaltconstruction.co.za/careers",
    fieldsOfStudy: ["Civil Engineering", "Quantity Surveying", "Construction Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-26",
    name: "Harvest AgriTech Bursary",
    provider: "Harvest AgriTech",
    description: "Funding for agricultural technology, agronomy and agri-business students.",
    amount: "Tuition + field placement",
    eligibilityCriteria: ["South African citizen", "Studying agri-tech or agronomy"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Harvest AgriTech",
    contactInfo: "careers@harvestagritech.co.za",
    website: "https://www.harvestagritech.co.za/careers",
    fieldsOfStudy: ["Agronomy", "Agritech", "Agribusiness"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-27",
    name: "Axis Renewable Bursary",
    provider: "Axis Renewable Energy",
    description: "Support for renewables, electrical engineering and energy systems students.",
    amount: "Tuition + project placement",
    eligibilityCriteria: ["South African citizen", "Studying renewable energy or electrical engineering"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Axis Renewable careers",
    contactInfo: "careers@axisrenewables.co.za",
    website: "https://www.axisrenewables.co.za/careers",
    fieldsOfStudy: ["Renewable Energy", "Electrical Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-28",
    name: "Helios Research Bursary",
    provider: "Helios Research Institute",
    description: "Bursary for STEM research students across disciplines.",
    amount: "Tuition + research stipend",
    eligibilityCriteria: ["South African citizen/permanent resident", "Postgraduate research candidates"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via Helios Research",
    contactInfo: "research@helios.org.za",
    website: "https://www.helios.org.za",
    fieldsOfStudy: ["Science", "Engineering", "Technology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic record", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-29",
    name: "Pioneer Foods Bursary",
    provider: "Pioneer Foods",
    description: "Support for food technology, nutrition and commerce students.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying food technology or nutrition"],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply via Pioneer Foods careers",
    contactInfo: "careers@pioneerfoods.co.za",
    website: "https://www.pioneerfoods.co.za/careers",
    fieldsOfStudy: ["Food Science", "Nutrition", "Commerce"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-30",
    name: "Vivid Design Bursary",
    provider: "Vivid Design Studios",
    description: "Funding for design, UX/UI and creative media students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying design or media"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Vivid Design Studios",
    contactInfo: "careers@vividdesign.co.za",
    website: "https://www.vividdesign.co.za/careers",
    fieldsOfStudy: ["Design", "UX/UI", "Creative Media"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Portfolio review required", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-31",
    name: "Crest Pharmaceuticals Bursary",
    provider: "Crest Pharmaceuticals",
    description: "Bursary for pharmacy, pharmacology and pharmaceutical science students.",
    amount: "Tuition + research placement",
    eligibilityCriteria: ["South African citizen", "Studying pharmacy or pharmacology"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Crest Pharmaceuticals careers",
    contactInfo: "careers@crestpharma.co.za",
    website: "https://www.crestpharma.co.za/careers",
    fieldsOfStudy: ["Pharmacy", "Pharmacology", "Pharmaceutical Sciences"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-32",
    name: "Harbor Education Trust Bursary",
    provider: "Harbor Education Trust",
    description: "Support for teacher education and foundation phase training.",
    amount: "Tuition + placement support",
    eligibilityCriteria: ["South African citizen", "Studying education"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Harbor Education Trust",
    contactInfo: "info@harboreducation.org.za",
    website: "https://www.harboreducation.org.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-33",
    name: "Nimbus Analytics Bursary",
    provider: "Nimbus Analytics",
    description: "Bursary for analytics, statistics and data science students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying statistics or data science"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Nimbus careers",
    contactInfo: "careers@nimbusanalytics.co.za",
    website: "https://www.nimbusanalytics.co.za/careers",
    fieldsOfStudy: ["Statistics", "Data Science"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-34",
    name: "Verdant Water Bursary",
    provider: "Verdant Water Solutions",
    description: "Support for water resource engineering and hydrology students.",
    amount: "Tuition + fieldwork",
    eligibilityCriteria: ["South African citizen", "Studying hydrology or water engineering"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Verdant Water careers",
    contactInfo: "careers@verdantwater.co.za",
    website: "https://www.verdantwater.co.za/careers",
    fieldsOfStudy: ["Hydrology", "Civil Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-35",
    name: "Signal Media Bursary",
    provider: "Signal Media Group",
    description: "Bursary for digital media, communications and journalism students.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying media/communications"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Signal Media careers",
    contactInfo: "careers@signalmedia.co.za",
    website: "https://www.signalmedia.co.za/careers",
    fieldsOfStudy: ["Media Studies", "Journalism", "Communications"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-36",
    name: "Atlas Labs Bursary",
    provider: "Atlas Labs",
    description: "Funding for laboratory sciences, microbiology and biomedical studies.",
    amount: "Tuition + lab placement",
    eligibilityCriteria: ["South African citizen", "Studying biomedical or lab sciences"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Atlas Labs careers",
    contactInfo: "careers@atlaslabs.co.za",
    website: "https://www.atlaslabs.co.za/careers",
    fieldsOfStudy: ["Biomedical Science", "Microbiology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-37",
    name: "Beacon Hospitality Bursary",
    provider: "Beacon Hospitality Group",
    description: "Bursary for hospitality management, culinary arts and tourism studies.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying hospitality or tourism"],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply via Beacon Hospitality careers",
    contactInfo: "careers@beaconhospitality.co.za",
    website: "https://www.beaconhospitality.co.za/careers",
    fieldsOfStudy: ["Hospitality Management", "Tourism", "Culinary Arts"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-38",
    name: "Pinnacle Rail Bursary",
    provider: "Pinnacle Rail",
    description: "Support for mechanical and electrical engineering students focusing on rail systems.",
    amount: "Tuition + practical training",
    eligibilityCriteria: ["South African citizen", "Studying mechanical or electrical engineering"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Pinnacle Rail careers",
    contactInfo: "careers@pinnaclerail.co.za",
    website: "https://www.pinnaclerail.co.za/careers",
    fieldsOfStudy: ["Mechanical Engineering", "Electrical Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-39",
    name: "Orbit Space Bursary",
    provider: "Orbit Space Technologies",
    description: "Bursary for satellite engineering, aerospace and orbital mechanics students.",
    amount: "Tuition + research support",
    eligibilityCriteria: ["South African citizen", "Studying aerospace or physics"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Orbit Space careers",
    contactInfo: "careers@orbitspace.co.za",
    website: "https://www.orbitspace.co.za/careers",
    fieldsOfStudy: ["Aerospace Engineering", "Physics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-40",
    name: "Harbor Social Impact Bursary",
    provider: "Harbor Social Impact Fund",
    description: "Funding for social work, community development and NGO management students.",
    amount: "Tuition + placement support",
    eligibilityCriteria: ["South African citizen", "Studying social work or community development"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Harbor Social Impact Fund",
    contactInfo: "info@harborsocialimpact.org.za",
    website: "https://www.harborsocialimpact.org.za",
    fieldsOfStudy: ["Social Work", "Community Development"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-41",
    name: "Cura Hospitals Bursary",
    provider: "Cura Hospitals Group",
    description: "Support for nursing, clinical and allied health students.",
    amount: "Tuition + clinical training",
    eligibilityCriteria: ["South African citizen", "Studying nursing or allied health"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Cura Hospitals careers",
    contactInfo: "careers@curahospitals.co.za",
    website: "https://www.curahospitals.co.za/careers",
    fieldsOfStudy: ["Nursing", "Clinical Sciences"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic standing", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-42",
    name: "Terra GreenTech Bursary",
    provider: "Terra GreenTech",
    description: "Bursary for sustainable agriculture, environmental engineering and green tech students.",
    amount: "Tuition + project placement",
    eligibilityCriteria: ["South African citizen", "Studying environmental or agri-tech"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Terra GreenTech careers",
    contactInfo: "careers@terragreentech.co.za",
    website: "https://www.terragreentech.co.za/careers",
    fieldsOfStudy: ["Environmental Engineering", "Sustainable Agriculture"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-43",
    name: "Harbor Tech Apprenticeship Bursary",
    provider: "Harbor Tech",
    description: "Support for apprenticeships in trades, electrical and mechanical fields with study support.",
    amount: "Tuition + apprenticeship stipend",
    eligibilityCriteria: ["South African citizen", "Studying technical trades or engineering"],
    applicationDeadline: "Varies",
    applicationProcess: "Apply via Harbor Tech apprenticeships",
    contactInfo: "apprenticeships@harbortech.co.za",
    website: "https://www.harbortech.co.za/apprenticeships",
    fieldsOfStudy: ["Trades", "Electrical", "Mechanical"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Trade readiness", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-44",
    name: "Orion Analytics Bursary",
    provider: "Orion Analytics",
    description: "Funding for analytics, AI and computational mathematics students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying analytics or applied mathematics"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Orion Analytics careers",
    contactInfo: "careers@orionanalytics.co.za",
    website: "https://www.orionanalytics.co.za/careers",
    fieldsOfStudy: ["Data Science", "Applied Mathematics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-45",
    name: "Delta Marine Bursary",
    provider: "Delta Marine",
    description: "Bursary for marine engineering, naval architecture and maritime logistics.",
    amount: "Tuition + sea-time placement",
    eligibilityCriteria: ["South African citizen", "Studying marine engineering or naval architecture"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Delta Marine careers",
    contactInfo: "careers@deltamarine.co.za",
    website: "https://www.deltamarine.co.za/careers",
    fieldsOfStudy: ["Marine Engineering", "Naval Architecture"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-46",
    name: "Praxis Legal Bursary",
    provider: "Praxis Legal",
    description: "Support for law students from disadvantaged backgrounds.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying law", "Financial need considered"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Praxis Legal bursary",
    contactInfo: "bursaries@praxislegal.co.za",
    website: "https://www.praxislegal.co.za/bursaries",
    fieldsOfStudy: ["Law"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-47",
    name: "Pulse HealthTech Bursary",
    provider: "Pulse HealthTech",
    description: "Bursary for health informatics, biomedical engineering and e-health students.",
    amount: "Tuition + research placement",
    eligibilityCriteria: ["South African citizen", "Studying health informatics or biomedical engineering"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Pulse HealthTech careers",
    contactInfo: "careers@pulsehealthtech.co.za",
    website: "https://www.pulsehealthtech.co.za/careers",
    fieldsOfStudy: ["Health Informatics", "Biomedical Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-48",
    name: "Silverline Maritime Bursary",
    provider: "Silverline Maritime",
    description: "Support for maritime operations and port logistics students.",
    amount: "Tuition + placement",
    eligibilityCriteria: ["South African citizen", "Studying maritime or logistics"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Silverline Maritime careers",
    contactInfo: "careers@silverlinemarine.co.za",
    website: "https://www.silverlinemarine.co.za/careers",
    fieldsOfStudy: ["Maritime Studies", "Logistics"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-49",
    name: "Lighthouse Social Bursary",
    provider: "Lighthouse Social Impact",
    description: "Funding for social entrepreneurship, NGO management and community development students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying social entrepreneurship or community development"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Lighthouse Social Impact",
    contactInfo: "info@lighthousesocial.org.za",
    website: "https://www.lighthousesocial.org.za",
    fieldsOfStudy: ["Social Entrepreneurship", "Community Development"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-50",
    name: "Vector Systems Bursary",
    provider: "Vector Systems",
    description: "Bursary for systems engineering, computer systems and embedded systems students.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying systems or embedded systems"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Vector Systems careers",
    contactInfo: "careers@vectorsystems.co.za",
    website: "https://www.vectorsystems.co.za/careers",
    fieldsOfStudy: ["Systems Engineering", "Computer Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-51",
    name: "Zenith Logistics Bursary",
    provider: "Zenith Logistics",
    description: "Support for supply chain, logistics and transport studies.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying logistics or supply chain"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Zenith Logistics careers",
    contactInfo: "careers@zenithlogistics.co.za",
    website: "https://www.zenithlogistics.co.za/careers",
    fieldsOfStudy: ["Logistics", "Supply Chain"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-52",
    name: "Aurora Arts Bursary",
    provider: "Aurora Arts Collective",
    description: "Bursary for performing arts, theatre and dance students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying performing arts"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Aurora Arts Collective",
    contactInfo: "info@auroraarts.co.za",
    website: "https://www.auroraarts.co.za",
    fieldsOfStudy: ["Performing Arts", "Dance", "Theatre"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Audition or portfolio required", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-53",
    name: "Polaris Biomed Bursary",
    provider: "Polaris Biomed",
    description: "Support for biomedical engineering, medical technology and clinical research students.",
    amount: "Tuition + research internship",
    eligibilityCriteria: ["South African citizen", "Studying biomedical or clinical research"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Polaris Biomed careers",
    contactInfo: "careers@polarisbiomed.co.za",
    website: "https://www.polarisbiomed.co.za/careers",
    fieldsOfStudy: ["Biomedical Engineering", "Medical Technology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-54",
    name: "Echo Solar Bursary",
    provider: "Echo Solar Solutions",
    description: "Bursary for solar PV, renewable energy and electrical engineering students.",
    amount: "Tuition + field placement",
    eligibilityCriteria: ["South African citizen", "Studying renewable energy or electrical engineering"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Echo Solar careers",
    contactInfo: "careers@echosolar.co.za",
    website: "https://www.echosolar.co.za/careers",
    fieldsOfStudy: ["Renewable Energy", "Electrical Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-55",
    name: "Atlas Foundation Bursary",
    provider: "Atlas Foundation",
    description: "Support for social sciences, public policy and community leadership students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying public policy or social sciences"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Atlas Foundation",
    contactInfo: "info@atlasfoundation.org.za",
    website: "https://www.atlasfoundation.org.za",
    fieldsOfStudy: ["Public Policy", "Social Sciences"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-56",
    name: "Crown IT Solutions Bursary",
    provider: "Crown IT Solutions",
    description: "Bursary for IT, cybersecurity and cloud computing students.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying IT or cybersecurity"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Crown IT careers",
    contactInfo: "careers@crownit.co.za",
    website: "https://www.crownit.co.za/careers",
    fieldsOfStudy: ["Information Technology", "Cybersecurity"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-57",
    name: "Horizon Civil Bursary",
    provider: "Horizon Civil Works",
    description: "Bursary for civil engineering and construction management students.",
    amount: "Tuition + practical training",
    eligibilityCriteria: ["South African citizen", "Studying civil engineering or construction management"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Horizon Civil careers",
    contactInfo: "careers@horizoncivil.co.za",
    website: "https://www.horizoncivil.co.za/careers",
    fieldsOfStudy: ["Civil Engineering", "Construction Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-58",
    name: "Nexus Bio Bursary",
    provider: "Nexus Bio",
    description: "Support for biochemistry, biotechnology and life sciences students.",
    amount: "Tuition + research stipend",
    eligibilityCriteria: ["South African citizen", "Studying biochemistry or biotechnology"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Nexus Bio careers",
    contactInfo: "careers@nexusbio.co.za",
    website: "https://www.nexusbio.co.za/careers",
    fieldsOfStudy: ["Biochemistry", "Biotechnology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-59",
    name: "Aegis Security Bursary",
    provider: "Aegis Security Services",
    description: "Bursary for security management, policing studies and forensics students.",
    amount: "Tuition + practical training",
    eligibilityCriteria: ["South African citizen", "Studying security or forensics"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Aegis careers",
    contactInfo: "careers@aegissecurity.co.za",
    website: "https://www.aegissecurity.co.za/careers",
    fieldsOfStudy: ["Forensics", "Security Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: false },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-60",
    name: "Helix Education Bursary",
    provider: "Helix Education Group",
    description: "Support for education technology, teaching and learning sciences students.",
    amount: "Tuition + practicum",
    eligibilityCriteria: ["South African citizen", "Studying education or edtech"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Helix Education",
    contactInfo: "info@helixeducation.co.za",
    website: "https://www.helixeducation.co.za",
    fieldsOfStudy: ["Education", "EdTech"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-61",
    name: "Praxis Energy Bursary",
    provider: "Praxis Energy",
    description: "Bursary for petroleum engineering, chemical engineering and energy studies.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying petroleum or chemical engineering"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Praxis Energy careers",
    contactInfo: "careers@praxisenergy.co.za",
    website: "https://www.praxisenergy.co.za/careers",
    fieldsOfStudy: ["Chemical Engineering", "Petroleum Engineering"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-62",
    name: "Aurora Pharma Bursary",
    provider: "Aurora Pharmaceuticals",
    description: "Support for pharmaceutical sciences and pharmacology students.",
    amount: "Tuition + research placement",
    eligibilityCriteria: ["South African citizen", "Studying pharmaceutical sciences"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Aurora Pharma careers",
    contactInfo: "careers@aurorapharma.co.za",
    website: "https://www.aurorapharma.co.za/careers",
    fieldsOfStudy: ["Pharmaceutical Sciences", "Pharmacology"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-63",
    name: "Solace Community Bursary",
    provider: "Solace Community Trust",
    description: "Funding for social work, early childhood education and community leadership students.",
    amount: "Tuition + placement support",
    eligibilityCriteria: ["South African citizen", "Studying social work or education"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Solace Community Trust",
    contactInfo: "info@solacetrust.org.za",
    website: "https://www.solacetrust.org.za",
    fieldsOfStudy: ["Social Work", "Early Childhood Education"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-64",
    name: "Nova Tech Bursary",
    provider: "Nova Tech Solutions",
    description: "Bursary for software engineering, full-stack development and cloud computing students.",
    amount: "Tuition + internship",
    eligibilityCriteria: ["South African citizen", "Studying software engineering or cloud computing"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Nova Tech careers",
    contactInfo: "careers@novatech.co.za",
    website: "https://www.novatech.co.za/careers",
    fieldsOfStudy: ["Software Engineering", "Cloud Computing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: true },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-65",
    name: "Pinnacle Health Bursary",
    provider: "Pinnacle Health Group",
    description: "Support for clinical nursing, midwifery and allied health students.",
    amount: "Tuition + clinical placements",
    eligibilityCriteria: ["South African citizen", "Studying nursing or allied health"],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply via Pinnacle Health careers",
    contactInfo: "careers@pinnaclehealth.co.za",
    website: "https://www.pinnaclehealth.co.za/careers",
    fieldsOfStudy: ["Nursing", "Midwifery", "Allied Health"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic standing", financialNeed: true },
    isActive: true,
    priority: "medium"
  },
  {
    id: "added-bursary-66",
    name: "Cobalt Finance Bursary",
    provider: "Cobalt Finance",
    description: "Bursary for accounting, actuarial science and finance students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying accounting, actuarial or finance"],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply via Cobalt Finance careers",
    contactInfo: "careers@cobaltfinance.co.za",
    website: "https://www.cobaltfinance.co.za/careers",
    fieldsOfStudy: ["Accounting", "Actuarial Science", "Finance"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 65% average", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-67",
    name: "Evergreen Forestry Bursary",
    provider: "Evergreen Forestry",
    description: "Support for forestry, environmental management and conservation students.",
    amount: "Tuition + fieldwork",
    eligibilityCriteria: ["South African citizen", "Studying forestry or environmental management"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Evergreen Forestry careers",
    contactInfo: "careers@evergreenforestry.co.za",
    website: "https://www.evergreenforestry.co.za/careers",
    fieldsOfStudy: ["Forestry", "Environmental Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Minimum 60% average", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-68",
    name: "Astra Quantum Bursary",
    provider: "Astra Quantum Labs",
    description: "Bursary for quantum computing, physics and applied mathematics students.",
    amount: "Tuition + research mentorship",
    eligibilityCriteria: ["South African citizen", "Studying quantum computing or physics"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Astra Quantum Labs",
    contactInfo: "research@astraquantum.co.za",
    website: "https://www.astraquantum.co.za",
    fieldsOfStudy: ["Physics", "Applied Mathematics", "Quantum Computing"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Excellent academic performance", financialNeed: false },
    isActive: true,
    priority: "high"
  },
  {
    id: "added-bursary-69",
    name: "Harbor Civic Bursary",
    provider: "Harbor Civic Foundation",
    description: "Support for civic engagement, public administration and leadership studies.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying public administration or leadership"],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply via Harbor Civic Foundation",
    contactInfo: "info@harborcivic.org.za",
    website: "https://www.harborcivic.org.za",
    fieldsOfStudy: ["Public Administration", "Leadership Studies"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "low"
  },
  {
    id: "added-bursary-70",
    name: "Vertex Innovation Bursary",
    provider: "Vertex Innovations",
    description: "Bursary for entrepreneurship, innovation and technology management students.",
    amount: "Tuition + mentorship",
    eligibilityCriteria: ["South African citizen", "Studying entrepreneurship or innovation management"],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply via Vertex Innovations",
    contactInfo: "info@vertexinnovations.co.za",
    website: "https://www.vertexinnovations.co.za",
    fieldsOfStudy: ["Entrepreneurship", "Innovation Management"],
    provinces: ["All provinces"],
    requirements: { academicRequirement: "Good academic performance", financialNeed: true },
    isActive: true,
    priority: "medium"
  }
];
